name: Publish Lambda Layer

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      layer-name:
        required: true
        type: string
      layer-version:
        description: 'In the form x.x.x -- will be changed to x_x_x in layer name.'
        required: true
        type: string
      architecture:
        description: '(optional) amd64 or arm64'
        required: false
        type: string
      prod-release:
        description: 'Release to dev or prod? (Default: dev)'
        required: true
        default: false
        type: boolean
      aws_region:
        description: 'Deploy to aws region (can be a json list or single region)'
        required: true
        type: string

    secrets:
      token:
        required: true


permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        aws_region: ${{ fromJson(github.event.inputs.aws_region) }}

    steps:

      - name: Construct Layer Name
        shell: bash
        run: |
          LAYER_NAME=${{ inputs.layer-name }}
          
          if [[ -z ${{ inputs.architecture }} ]]; then
            LAYER_NAME=$LAYER_NAME-${{ inputs.architecture }}
          fi
          
          if [[ ${{ inputs.release-type }} != "prod" ]]; then
            LAYER_NAME=$LAYER_NAME-${{ inputs.release-type }}
          fi
          
          LAYER_VERSION=${{ inputs.layer-version }}
          LAYER_VERSION_CLEANED=$(echo "$LAYER_VERSION" | sed -r 's/\./_/g')
          
          LAYER_NAME=$LAYER_NAME-$LAYER_VERSION_CLEANED
          echo "LAYER_NAME=$LAYER_NAME" >> $GITHUB_ENV
          
          echo GITHUB_ENV:
          cat $GITHUB_ENV
    
          if [[ $GITHUB_REF_NAME != *$LAYER_VERSION ]]; then
            echo "Tag $GITHUB_REF_NAME doesn't end with $LAYER_VERSION"
            return 1
          fi

      - name: Download built layer
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.PROD_LAMBDA_ROLE_ARN }}
          role-duration-seconds: 1200
          aws-region: ${{ matrix.aws_region }}
          mask-aws-account-id: false

      - name: Publish Lambda Layer
        env:
          LAYER_VERSION: ${{needs.build.outputs.LAYER_VERSION}}
        run: |
          aws lambda publish-layer-version \
          --layer-name $LAYER_NAME \
          --license-info "Apache 2.0" \
          --zip-file fileb://${{ inputs.artifact-name }}
